### ISSUE TITLE
Crashes when exported

### ISSUE THREAD

**Issue by JonnyMqc** [Foreheadchann/ViaMCP-Reborn#13]
This works great and I appreciate it, but when I export my client to the normal minecraft launcher instead of eclipse, when I go to the GuiProtocolSelector it crashes. This doesn't happen in eclipse. I think it's something to do with the libs, can you help pls

**Comment by JonnyMqc** [comment]
java.lang.NoClassDefFoundError: com/viaversion/viaversion/api/protocol/version/ProtocolVersion
	at viamcp.protocols.ProtocolCollection.<clinit>(ProtocolCollection.java:9)
	at viamcp.gui.GuiProtocolSelector$SlotList.getSize(GuiProtocolSelector.java:86)
	at net.minecraft.client.gui.GuiSlot.getContentHeight(GuiSlot.java:123)
	at net.minecraft.client.gui.GuiSlot.func_148135_f(GuiSlot.java:181)
	at net.minecraft.client.gui.GuiSlot.bindAmountScrolled(GuiSlot.java:164)
	at net.minecraft.client.gui.GuiSlot.drawScreen(GuiSlot.java:235)
	at viamcp.gui.GuiProtocolSelector.drawScreen(GuiProtocolSelector.java:64)
	at net.minecraft.client.renderer.EntityRenderer.updateCameraAndRender(EntityRenderer.java:1414)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1143)
	at net.minecraft.client.Minecraft.run(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(Main.java:117)
Caused by: java.lang.ClassNotFoundException: com.viaversion.viaversion.api.protocol.version.ProtocolVersion
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 11 more
