### ISSUE TITLE
Hey is the Old ViaMcp problems are fixed? there was lots of erros about Packets

### ISSUE THREAD

**Issue by Godwhitelight** [Foreheadchann/ViaMCP-Reborn#2]

**Comment by Foreheadchann** [comment]
I am not sure, i never got errors with packets on the original ViaMCP

**Comment by Godwhitelight** [comment]
I will send here 1 moment checking if there is errors

**Comment by Godwhitelight** [comment]
yes the errors staying.

Caused by: java.lang.NullPointerException
	at net.minecraft.scoreboard.Scoreboard.removeTeam(Scoreboard.java:296) ~[bin/:?]
	at net.minecraft.client.network.NetHandlerPlayClient.handleTeams(NetHandlerPlayClient.java:1995) ~[bin/:?]
	at net.minecraft.network.play.server.S3EPacketTeams.processPacket(S3EPacketTeams.java:140) ~[bin/:?]
	at net.minecraft.network.play.server.S3EPacketTeams.processPacket(S3EPacketTeams.java:12) ~[bin/:?]
	at net.minecraft.network.PacketThreadUtil$1.run(PacketThreadUtil.java:15) ~[bin/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_292]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_292]
	at net.minecraft.util.Util.func_181617_a(Util.java:19) ~[bin/:?]
	... 4 more
	
	Here is the error if you know how to fix

**Comment by Foreheadchann** [comment]
This is not caused by viaversion, and it is a server sided issue (happens also on tree.ac)
